/* opensslv.h */

#ifndef HEADER_OPENSSLV_H
#define HEADER_OPENSSLV_H

#define OPENSSL_VERSION_NUMBER	0x0090702fL
#define OPENSSL_VERSION_TEXT	"OpenSSL 0.9.7b 10 Apr 2003"
#define OPENSSL_VERSION_PTEXT	" part of " OPENSSL_VERSION_TEXT

#define SHLIB_VERSION_HISTORY ""
#define SHLIB_VERSION_NUMBER "0.9.7"


#endif
